blank_issues_enabled: true
contact_links:
  - name: XTend.search development guide
    url: https://github.com/konnilabs/xtend-search/blob/main/CONTRIBUTING.md
    about: Build, tests and contribution workflow
