import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const base=process.env.TEST_BASE_URL||'http://localhost:8093',out=new URL('../../evidence/control-plane/',import.meta.url),checks=[];
await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true});
async function login(role){const context=await browser.newContext({viewport:{width:1440,height:1000},colorScheme:'dark'}),page=await context.newPage();await page.goto(base+'/admin');await page.getByRole('button',{name:'Anmelden mit CCS Account',exact:true}).or(page.getByRole('link',{name:'Anmelden mit CCS Account',exact:true})).click();await page.getByRole('link',{name:role,exact:true}).click();await page.waitForURL(base+'/admin');await page.waitForFunction(()=>Boolean(window.XTendPage));return {context,page};}
let admin;
try{
 admin=await login('administrator');const {page,context}=admin,errors=[];let saveRequest;
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/admin.engine.policy.set'))saveRequest=JSON.parse(r.postData());});
 await page.waitForFunction(()=>document.querySelectorAll('.engine-choice').length>=6);assert.ok(await page.locator('.engine-choice').count()>=6);
 const timeOrigin=await page.evaluate(()=>performance.timeOrigin);
 for(const [id,capability]of [['fixture fast','general'],['fixture medium','general'],['fixture slow','general'],['fixture images','images'],['fixture news','news'],['fixture videos','videos']]){
  await page.locator('.engine-choice').filter({hasText:id}).click();await page.waitForFunction(id=>document.querySelector('.engine-detail h3')?.textContent===id,id);
  const before=await page.locator('#policy-form input[name=revision]').inputValue();
  await page.locator('#policy-form select[name=state]').selectOption('allowed');await page.locator('#policy-form input[name=capabilities]').fill(capability);await page.locator('#policy-form input[name=rpm]').fill('60');await page.locator('#policy-form input[name=concurrency]').fill('4');await page.locator('#policy-form input[name=family]').fill(id.replaceAll(' ','-'));await page.locator('#policy-form input[name=pagingVerified]').check();
  await page.getByRole('button',{name:'Policy verbindlich speichern'}).click();await page.waitForFunction(before=>document.querySelector('#policy-form input[name=revision]').value!==before,before);
  assert.match(await page.locator('.admin-message').textContent(),/Audit gespeichert/);
  assert.match(await page.locator('.engine-choice.selected').textContent(),/Freigegeben/);
 }
 assert.equal(await page.evaluate(()=>performance.timeOrigin),timeOrigin);checks.push('All six engine policies persisted through real RMT actions; source navigation resumes without document reload.');
 const csrf=await page.locator('meta[name=csrf-token]').getAttribute('content');
 const rejected=await context.request.post(base+'/api/xtend/services/admin.engine.policy.set',{headers:{Origin:base},data:saveRequest});assert.equal(rejected.status(),403);
 const stale={...saveRequest,input:{...saveRequest.input,requestKey:randomUUID(),revision:'0'}};
 const conflict=await context.request.post(base+'/api/xtend/services/admin.engine.policy.set',{headers:{Origin:base,'X-CSRF-Token':csrf},data:stale});assert.equal((await conflict.json()).ok,false);checks.push('CSRF and stale revisions rejected by HTTP service boundary.');
 await page.locator('#routing-form select').selectOption('adaptive');await page.getByRole('button',{name:'Betriebsmodus speichern'}).click();await page.waitForFunction(()=>window.XTendPage.getRuntime().model.getState('admin.data').mode==='adaptive');
 await page.locator('#routing-form select').selectOption('conservative');await page.getByRole('button',{name:'Betriebsmodus speichern'}).click();await page.waitForFunction(()=>window.XTendPage.getRuntime().model.getState('admin.data').mode==='conservative');checks.push('Routing mode commands update canonical state and audit.');
 await page.screenshot({path:new URL('admin-desktop.png',out).pathname,fullPage:true});
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.ok(parseFloat(await page.locator('#policy-form input[name=rpm]').evaluate(e=>getComputedStyle(e).fontSize))>=16);await page.screenshot({path:new URL('admin-mobile.png',out).pathname,fullPage:true});await page.setViewportSize({width:720,height:600});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));checks.push('Mobile and 200%-equivalent layout remain within viewport; input size >=16px.');
 await page.setViewportSize({width:1440,height:1000});
 const publicPage=await context.newPage();let streamEncoding=null;publicPage.on('response',r=>{if(r.url().endsWith('/search.run'))streamEncoding=r.headers()['content-encoding']||'identity';});await publicPage.goto(base+'/');await publicPage.waitForFunction(()=>window.XTendPage);const origin=await publicPage.evaluate(()=>performance.timeOrigin);
 await publicPage.evaluate(()=>{window.testStart=0;window.testFrames=[];window.addEventListener('xtend-search:stream',e=>{const nodes=[...document.querySelectorAll('article.result')];window.testFrames.push({elapsed:performance.now()-window.testStart,status:e.detail.status,titles:nodes.map(n=>n.querySelector('h2')?.textContent),boxes:nodes.map(n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height};})});});});
 await publicPage.locator('#search-input').fill('open source');await publicPage.evaluate(()=>window.testStart=performance.now());await publicPage.getByRole('button',{name:'Suchen',exact:true}).click();await publicPage.waitForFunction(()=>window.testFrames.some(f=>f.status==='complete'),{},{timeout:15000});
 const frames=await publicPage.evaluate(()=>window.testFrames),batches=frames.filter(f=>f.titles.length);assert.ok(batches.length>=3);assert.ok(batches[0].elapsed<2000,JSON.stringify(frames));assert.ok(batches.at(-1).elapsed-batches[0].elapsed>1000);assert.equal(await publicPage.evaluate(()=>performance.timeOrigin),origin);
 for(const frame of batches.slice(1)){assert.deepEqual(frame.titles.slice(0,batches[0].titles.length),batches[0].titles);for(let i=0;i<batches[0].boxes.length;i++){assert.ok(Math.abs(frame.boxes[i].y-batches[0].boxes[i].y)<2);assert.ok(Math.abs(frame.boxes[i].width-batches[0].boxes[i].width)<2);}}
 await fs.writeFile(new URL('paint.json',out),JSON.stringify({deployment:'Docker frontend + private SearXNG backend + flushing gzip proxy',streamEncoding,frames,firstPaintMs:batches[0].elapsed,completeMs:batches.at(-1).elapsed},null,2));assert.equal(streamEncoding,'gzip');checks.push('Three delayed engines paint incrementally, append without moving existing results, and preserve the document.');
 await publicPage.screenshot({path:new URL('search-streamed.png',out).pathname,fullPage:true});
 await publicPage.locator('#search-input').fill('old query');await publicPage.getByRole('button',{name:'Suchen',exact:true}).click();await publicPage.waitForTimeout(180);await publicPage.locator('#search-input').fill('new query');await publicPage.getByRole('button',{name:'Suchen',exact:true}).click();await publicPage.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');assert.equal(await publicPage.locator('#search-input').inputValue(),'new query');assert.ok(!(await publicPage.locator('.result-list').textContent()).includes('old query'));checks.push('A superseded query cannot commit into the new result surface.');
 await publicPage.getByRole('link',{name:'Nachrichten',exact:true}).click();await publicPage.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');assert.ok(await publicPage.locator('article.result').count());await publicPage.goBack();await publicPage.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');assert.equal(await publicPage.evaluate(()=>window.XTendPage.page.props['search.data'].state.category),'general');checks.push('News mode and browser back navigation work.');
 const nojs=await browser.newContext({javaScriptEnabled:false}),np=await nojs.newPage();await np.goto(base+'/search?q=nojs&categories=general&language=all&safesearch=1');assert.ok(await np.locator('article.result').count());assert.equal(await np.locator('form[role=search]').count(),1);await nojs.close();checks.push('Direct SSR search remains useful without JavaScript.');
 const viewer=await login('viewer');assert.equal(await viewer.page.getByRole('button',{name:'Policy verbindlich speichern'}).isEnabled(),false);const viewerCsrf=await viewer.page.locator('meta[name=csrf-token]').getAttribute('content');const denied=await viewer.context.request.post(base+'/api/xtend/services/admin.engine.policy.set',{headers:{Origin:base,'X-CSRF-Token':viewerCsrf},data:saveRequest});assert.equal((await denied.json()).ok,false);await viewer.context.close();checks.push('Viewer cannot mutate through UI or direct service requests.');
 const operator=await login('operator');await operator.page.locator('.engine-choice').filter({hasText:'fixture videos'}).click();await operator.page.waitForFunction(()=>document.querySelector('.engine-detail h3')?.textContent==='fixture videos');assert.equal(await operator.page.getByRole('button',{name:'Policy verbindlich speichern'}).isEnabled(),false);await operator.page.getByRole('button',{name:'Budgetierte Probe vormerken'}).click();await operator.page.waitForFunction(()=>document.querySelector('.admin-message')?.textContent.includes('Probe vorgemerkt'));await operator.page.locator('#drain-form input[name=minutes]').fill('1');await operator.page.locator('#drain-form button[type=submit]').click();await operator.page.waitForFunction(()=>document.querySelector('.admin-message')?.textContent.includes('Audit gespeichert'));assert.match(await operator.page.locator('.engine-detail').textContent(),/Drain bis/);await operator.context.close();checks.push('Operator can schedule a budgeted probe and drain a source, but cannot approve policies.');assert.deepEqual(errors,[]);await fs.writeFile(new URL('browser.json',out),JSON.stringify({ok:true,checks},null,2));console.log(JSON.stringify({ok:true,checks}));
}catch(error){await admin?.page.screenshot({path:new URL('browser-failure.png',out).pathname,fullPage:true}).catch(()=>{});console.error(error);process.exitCode=1;}finally{await browser.close();}
