import {chromium} from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';
const browser=await chromium.launch(),base=process.env.TEST_BASE_URL||'http://localhost:8093',checks=[];
try{
 const context=await browser.newContext(),page=await context.newPage();page.on('pageerror',e=>console.log('pageerror',e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().includes('/media?'))console.log('http',r.status(),r.url());});await page.goto(base+'/');await page.waitForFunction(()=>window.XTendPage);
 // Protocol violations use the canonical transport and actual app error UI.
 await page.route('**/api/xtend/services/search.run',route=>route.fulfill({status:200,contentType:'application/x-ndjson',body:'{malformed}\n'}));await page.locator('#search-input').fill('interrupted');await page.getByRole('button',{name:'Suchen',exact:true}).click();await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='error');assert.match(await page.locator('.result-list').textContent(),/unterbrochen/);checks.push('Malformed stream reaches a visible terminal error without retry/fan-out.');await page.unroute('**/api/xtend/services/search.run');
 await page.route('**/media?*',async route=>{const url=new URL(route.request().url()),u=Buffer.from(url.searchParams.get('u'),'base64url').toString();if(u.includes('/0.png')||u.includes('/thumb-0'))return route.fulfill({status:403,body:''});return route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64')});});
 await page.getByRole('link',{name:'Bilder',exact:true}).click();await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');await page.locator('.image-results article').first().waitFor();await page.waitForFunction(()=>document.querySelector('.image-results article img')?.getAttribute('src')?.includes('image-placeholder'));
 await page.locator('[data-preview-id]').first().click();await page.waitForTimeout(500);await page.locator('[data-preview-id]').nth(1).click();await page.waitForFunction(()=>document.querySelector('.preview-position')?.textContent==='Bild 2 von 4');await page.locator('#preview-expand').click();await page.waitForFunction(()=>document.querySelector('x-lightbox')?.hasAttribute('open'));await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.querySelector('.lightbox-position')?.textContent==='Bild 3 von 4');await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('x-lightbox')?.hasAttribute('open')); checks.push('Blocked image uses placeholder; preview remains switchable and XLightbox opens the current-page carousel.');
 await page.locator('#search-input').fill('paging');await page.getByRole('button',{name:'Suchen',exact:true}).click();await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');await page.getByRole('link',{name:'Nächste Seite →'}).click();await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].page===2&&window.XTendPage.page.props['search.data'].stream?.phase==='complete');assert.ok(await page.locator('article.result').count());checks.push('Signed pagination retains engine plan and category.');
 for(const fault of ['duplicate','incomplete']){
  await page.route('**/api/xtend/services/search.run',async route=>{const response=await route.fetch(),lines=(await response.text()).trim().split('\n');const body=fault==='duplicate'?[lines[0],lines[1],lines[1],...lines.slice(2)]:lines.slice(0,-1);await route.fulfill({status:200,contentType:'application/x-ndjson',body:body.join('\n')+'\n'});});
  await page.locator('#search-input').fill(fault);await page.getByRole('button',{name:'Suchen',exact:true}).click();await page.waitForFunction(()=>['complete','error'].includes(window.XTendPage.page.props['search.data'].stream?.phase));
  const result=await page.evaluate(()=>window.XTendPage.page.props['search.data']);assert.equal(new Set(result.results.map(r=>r.id)).size,result.results.length);if(fault==='incomplete')assert.equal(result.stream.phase,'error');
  await page.unroute('**/api/xtend/services/search.run');checks.push(fault+' frames settle without duplicate results or automatic retries.');
 }
 console.log(JSON.stringify({ok:true,checks}));await fs.writeFile(new URL('../../evidence/control-plane/edge-browser.json',import.meta.url),JSON.stringify({ok:true,checks},null,2));
}finally{await browser.close();}
