import test from 'node:test';
import assert from 'node:assert/strict';
import {NextcloudAuth} from '../../server/control/auth.mjs';
import {SearxAdapter,PINNED} from '../../server/control/adapter.mjs';
import {MediaProxy} from '../../server/control/media.mjs';
const environment={PUBLIC_BASE_URL:'https://search.example.org',NEXTCLOUD_BASE_URL:'https://cloud.example.org/cloud/',NEXTCLOUD_CLIENT_ID:'fixture',NEXTCLOUD_CLIENT_SECRET:'fixture-only',XTEND_ADMIN_ROLES:'{"alice":"administrator","reader":"viewer"}'};
function response(){return {headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},writeHead(status,headers={}){this.status=status;Object.entries(headers).forEach(([k,v])=>this.setHeader(k,v));},end(){this.ended=true;}};}
function flow(auth){const res=response();auth.begin({headers:{}},res);return {state:new URL(res.headers.location).searchParams.get('state'),cookie:res.headers['set-cookie'].split(';')[0],res};}
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json',...headers}});
const cloud=async(url,init)=>url.pathname.endsWith('/token')?json({token_type:'Bearer',access_token:'temporary-fixture',refresh_token:'never-store',user_id:'alice'}):json({ocs:{meta:{status:'ok'},data:{id:'alice'}}});
test('OAuth authorization pins the full subdirectory and production callback; only secure HttpOnly cookies',()=>{const auth=new NextcloudAuth({env:environment}),{res}=flow(auth),u=new URL(res.headers.location);assert.equal(u.pathname,'/cloud/apps/oauth2/authorize');assert.equal(u.searchParams.get('redirect_uri'),'https://search.example.org/admin/oauth/callback');assert.match(res.headers['set-cookie'],/^__Host-xtend-flow=/);assert.match(res.headers['set-cookie'],/HttpOnly; SameSite=Lax.*Secure/);assert.ok(!res.headers.location.includes('fixture-only'));});
test('OAuth state is browser-bound and single-use',async()=>{const auth=new NextcloudAuth({env:environment,fetchImpl:cloud}),f=flow(auth),url=new URL('https://search.example.org/admin/oauth/callback?'+new URLSearchParams({state:f.state,code:'code'}));await assert.rejects(()=>auth.callback({headers:{cookie:'xtend-flow=wrong'}},response(),url));await assert.rejects(()=>auth.callback({headers:{cookie:f.cookie}},response(),url));assert.equal(auth.sessions.size,0);});
test('OAuth uses authenticated OCS identity; session keeps neither access nor refresh tokens',async()=>{const auth=new NextcloudAuth({env:environment,fetchImpl:cloud}),f=flow(auth),res=response();await auth.callback({headers:{cookie:f.cookie}},res,new URL('https://search.example.org/admin/oauth/callback?'+new URLSearchParams({state:f.state,code:'fixture-code'})));assert.equal(res.status,303);const req={headers:{cookie:res.headers['set-cookie'].split(';')[0]}},ctx=auth.context(req);assert.equal(ctx.role,'administrator');assert.ok(!JSON.stringify([...auth.sessions]).includes('temporary-fixture'));assert.ok(!JSON.stringify([...auth.sessions]).includes('never-store'));assert.throws(()=>auth.protect(req));assert.throws(()=>auth.protect({headers:{...req.headers,origin:'https://evil.example','x-csrf-token':ctx.csrf}}));assert.equal(auth.protect({headers:{...req.headers,origin:environment.PUBLIC_BASE_URL,'x-csrf-token':ctx.csrf}}).actor,'alice');});
test('mismatched identities and accounts without explicit roles cannot sign in',async()=>{for(const id of ['mallory','reader']){const auth=new NextcloudAuth({env:environment,fetchImpl:async(url,init)=>url.pathname.endsWith('/token')?cloud(url,init):json({ocs:{meta:{status:'ok'},data:{id}}})}),f=flow(auth);await assert.rejects(()=>auth.callback({headers:{cookie:f.cookie}},response(),new URL('https://search.example.org/admin/oauth/callback?'+new URLSearchParams({state:f.state,code:'code'}))));assert.equal(auth.sessions.size,0);}});
test('unencrypted public admin origins are refused; local testing remains possible',()=>{assert.throws(()=>new NextcloudAuth({env:{...environment,PUBLIC_BASE_URL:'http://public.example'}}));assert.doesNotThrow(()=>new NextcloudAuth({env:{...environment,PUBLIC_BASE_URL:'http://localhost:8090'}}));});
const catalog={version:PINNED+'+fixture',plugins:[],engines:[{name:'engine one',categories:['general','news'],enabled:true,paging:true,language_support:true,languages:['en','de'],safesearch:true,time_range_support:true,timeout:3}]};
const capHeaders={'X-XTend-Backend-Contract':'engine-json-v1'};
const query={q:'site:example.org fox',category:'general',page:1,language:'all',safeSearch:'1',timeRange:''};
test('adapter attests pinned backend, inactive plugins, and never treats discovery as health',async()=>{for(const [data,headers] of [[{...catalog,version:'future'},capHeaders],[{...catalog,plugins:[{enabled:true}]},capHeaders],[catalog,{}]]){const a=new SearxAdapter({baseUrl:'http://backend/',token:'fixture',fetchImpl:async()=>json(data,200,headers)});await assert.rejects(()=>a.discover());assert.equal(a.catalog.size,0);}const a=new SearxAdapter({baseUrl:'http://backend/',token:'fixture',fetchImpl:async()=>json(catalog,200,capHeaders)});await a.discover();assert.equal(a.status,'compatible');assert.ok(!('health' in a.catalog.get('engine one')));});
test('engine request contains only explicit reviewed fields, no categories, cookies, or browser engine_data',async()=>{let request;const a=new SearxAdapter({baseUrl:'http://backend/',token:'fixture',fetchImpl:async(url,init)=>{if(url.pathname==='/config')return json(catalog,200,capHeaders);request=init;return json({results:[{url:'https://example.org',title:'<b>fox</b>',engines:['engine one']}],unresponsive_engines:[],infoboxes:[]});}});await a.discover();const r=await a.execute(a.catalog.get('engine one'),{...query,categories:'news',engines:'other',cookies:'unsafe',engine_data:'unsafe'},AbortSignal.timeout(1000));assert.equal(r.outcome,'success');assert.equal(r.results[0].title,'fox');assert.deepEqual([...request.body.keys()].sort(),['engines','format','language','pageno','q','safesearch','time_range'].sort());assert.equal(request.body.get('engines'),'engine one');assert.ok(!request.headers.Cookie);await assert.rejects(()=>a.execute(a.catalog.get('engine one'),{...query,q:'!google canary'},AbortSignal.timeout(1000)));});
test('HTTP200 provider errors, unsafe URLs and foreign attribution never become successful results',async()=>{for(const [payload,expected]of [[{results:[],unresponsive_engines:[['engine one','CAPTCHA']]},'captcha'],[{results:[{url:'javascript:alert(1)',engines:['engine one']}],unresponsive_engines:[]},'unsafe_url_scheme'],[{results:[{url:'https://example.org',engines:['unapproved']}],unresponsive_engines:[]},'schema_invalid']]){const a=new SearxAdapter({baseUrl:'http://backend/',token:'fixture',fetchImpl:async url=>url.pathname==='/config'?json(catalog,200,capHeaders):json(payload)});await a.discover();const r=await a.execute(a.catalog.get('engine one'),query,AbortSignal.timeout(1000));assert.equal(r.outcome,'error');assert.equal(r.errorClass,expected);}});
test('backend 429 remains backend ingress scope and retains Retry-After',async()=>{const a=new SearxAdapter({baseUrl:'http://backend/',token:'fixture',fetchImpl:async url=>url.pathname==='/config'?json(catalog,200,capHeaders):json({},429,{'Retry-After':'7200'})});await a.discover();const r=await a.execute(a.catalog.get('engine one'),query,AbortSignal.timeout(1000));assert.equal(r.errorClass,'backend_ingress_limit');assert.ok(r.retryNotBefore>Date.now()+7199000);});
test('media proxy refuses unsigned requests and signed internal targets before any network read',async()=>{const media=new MediaProxy('fixture-only');for(const path of ['/media?u=garbage&exp=9999999999&h=unsigned',media.sign('http://127.0.0.1:80/private'),media.sign('http://[::ffff:127.0.0.1]/private')]){const res=response();res.on=()=>{};await media.handle({},res,new URL(path,'http://localhost'));assert.ok([403,502].includes(res.status));}assert.equal(media.active,0);});
