use_default_settings:
  engines:
    keep_only: []
general:
  instance_name: "XTend.search"
  enable_metrics: false
server:
  secret_key: "replaced-by-SEARXNG_SECRET"
  limiter: false
  public_instance: false
  image_proxy: true
search:
  formats: [html, json]
  safe_search: 1
  autocomplete: ""
  default_lang: "all"
  favicon_resolver: ""
ui:
  default_locale: "de"
  default_theme: "simple"
  simple_style: "light"
  infinite_scroll: false
outgoing:
  request_timeout: 5.0
  max_request_timeout: 10.0
preferences:
  lock: [autocomplete, image_proxy]
engines:
  - name: xtend fixture
    engine: xtend_fixture
    shortcut: xtfixture
    disabled: false
    categories: [general, images]
  - name: xtend fixture slow
    engine: xtend_fixture_slow
    shortcut: xtslow
    disabled: false
    categories: [general, images]
