import assert from 'node:assert/strict';
import fs from 'node:fs';
import {chromium} from 'playwright';
const base=process.env.TEST_BASE_URL || 'http://127.0.0.1:8080';
const query=process.env.SMOKE_QUERY || 'open web standards';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];const external=[];
page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(new URL(request.url()).origin!==base)external.push(request.url());});
const health=await fetch(base+'/health/ready');assert.equal(health.status,200);
await page.goto(base);await page.waitForFunction(()=>window.XTendPage);assert.equal(await page.locator('[data-rmt-resume-status]').first().getAttribute('data-rmt-resume-status'),'resumed');
await page.screenshot({path:'evidence/tests/product-home.png',fullPage:true});
await page.evaluate(()=>window.__documentIdentity='live-smoke');await page.locator('#search-input').fill(query);await page.locator('#search-input').press('Enter');
await page.waitForFunction(q=>{const d=window.XTendPage?.page?.props?.['search.data'];return d?.q===q && (!d.stream || d.stream.phase==='complete');},query,{timeout:25000});
const state=await page.evaluate(()=>({fixture:window.XTendPage.page.props['search.data'].fixture,count:document.querySelectorAll('article').length,warnings:window.XTendPage.page.props['search.data'].warnings,sameDocument:window.__documentIdentity==='live-smoke',status:document.querySelector('[data-rmt-resume-status]')?.getAttribute('data-rmt-resume-status')}));
assert.equal(state.fixture,false);assert.ok(state.count>0,'Live engines must return at least one usable result');assert.equal(state.sameDocument,true);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
await page.screenshot({path:'evidence/tests/product-results.png',fullPage:true});
await page.getByRole('link',{name:'Bilder',exact:true}).click();await page.waitForFunction(()=>{const d=window.XTendPage?.page?.props?.['search.data'];return d?.category==='images' && (!d.stream || d.stream.phase==='complete');},null,{timeout:25000});
const images=await page.evaluate(()=>({count:document.querySelectorAll('article').length,thumbnails:document.querySelectorAll('article img').length,proxied:Array.from(document.querySelectorAll('article img')).every(img=>new URL(img.src).pathname==='/image_proxy')}));assert.equal(images.proxied,true);
await page.goto(base+'/info/de/about');assert.match(await page.locator('body').innerText(),/Powered by SearXNG/);await page.screenshot({path:'evidence/tests/product-about.png',fullPage:true});
const source=await fetch(base+'/source.tar.gz',{method:'HEAD'});assert.equal(source.status,200);
await browser.close();fs.writeFileSync('evidence/tests/docker-live-smoke.json',JSON.stringify({timestamp:new Date().toISOString(),base,query,state,images,errors,externalBrowserRequests:external.length,health:health.status,sourceDownload:source.status},null,2));console.log(JSON.stringify({state,images,errors}));
