import {chromium} from 'playwright';import fs from 'node:fs';import assert from 'node:assert/strict';
const base=process.env.TEST_BASE_URL || 'http://127.0.0.1:8080';
for(let i=0;i<30;i++){let ready=false;try{ready=(await fetch(base+'/health/ready')).ok;}catch{}if(ready)break;if(i===29)throw Error('Service not ready');await new Promise(r=>setTimeout(r,500));}
const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'dark'}),errors=[],external=[];page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base))external.push(r.url());});
try{
 await page.goto(base+'/search?q=Mozilla%20Firefox&categories=images&language=de');await page.waitForFunction(()=>window.XTendPage);
 const data=await page.evaluate(()=>{const d=window.XTendPage.page.props['search.data'];return {q:d.q,fixture:d.fixture,results:d.results.length,previews:d.results.filter(r=>r.previewId).length};});assert.equal(data.fixture,false);assert.ok(data.previews>0);await page.evaluate(()=>window.__lightboxDocument=document);
 const preferred=page.getByRole('link',{name:/Bildvorschau: About Mozilla Firefox dialog/});await (await preferred.count()?preferred.first():page.locator('a[data-preview-id]').first()).click();await page.locator('#preview-expand').click();await page.locator('x-lightbox[open]').waitFor();await page.waitForFunction(()=>!document.getElementById('search-lightbox').hasAttribute('data-loading'));
 const opened=await page.locator('x-lightbox').evaluate(e=>({snapshot:e.snapshot(),title:e.querySelector('.lightbox-title').textContent,position:e.querySelector('.lightbox-position').textContent,imageLoaded:!!e.shadowRoot.querySelector('[part~="media"]').naturalWidth,message:e.querySelector('.lightbox-message').textContent}));await page.screenshot({animations:'disabled',path:'evidence/tests/lightbox/live-desktop.png'});
 await page.keyboard.press('End');await page.waitForFunction(n=>document.querySelector('.lightbox-position').textContent===`Bild ${n} von ${n}`,data.previews);await page.keyboard.press('ArrowRight');await page.waitForFunction(n=>document.querySelector('.lightbox-position').textContent===`Bild 1 von ${n}`,data.previews);await page.waitForFunction(()=>document.querySelector('.preview-position').textContent.startsWith('Bild 1 von'));
 await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.getElementById('search-lightbox').hasAttribute('open'));
 const closed=await page.evaluate(()=>({sameDocument:document===window.__lightboxDocument,focus:document.activeElement.id,expectedFocus:document.getElementById('preview-expand')?'preview-expand':'preview-close',sidebar:!!document.getElementById('image-preview')}));assert.equal(closed.sameDocument,true);assert.equal(closed.focus,closed.expectedFocus);assert.equal(closed.sidebar,true);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 const report={timestamp:new Date().toISOString(),data,opened,fullPageCarousel:true,wraparound:true,closed,errors,externalRequests:external.length,health:(await fetch(base+'/health/ready')).status};fs.writeFileSync('evidence/tests/lightbox/live.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}finally{await browser.close();}
