import assert from 'node:assert/strict';
import fs from 'node:fs';
import {chromium,firefox} from 'playwright';
import {createHttpAppServiceTransport} from '@ccslabs/xtend/maraca/app-services';
const base=process.env.TEST_BASE_URL || 'http://127.0.0.1:8093';
const out='evidence/tests/streaming';fs.mkdirSync(out,{recursive:true});
const rows=[];
const search=q=>'/search?'+new URLSearchParams({q,categories:'general',language:'all',safesearch:'1'});
const http=createHttpAppServiceTransport({baseUrl:base,pathPrefix:'/api/xtend/services'});
const start=performance.now(),frames=[];
for await(const frame of http.stream({serviceId:'search.results',kind:'stream',target:'server',input:{url:search('stream test')},invocationId:'test-stream',correlationId:'test-stream',signal:AbortSignal.timeout(15000)}))frames.push({...frame,at:performance.now()-start});
assert.equal(frames[0].type,'start');assert.equal(frames.at(-1).type,'complete');
assert.equal(frames.filter(f=>['complete','error','cancelled'].includes(f.type)).length,1);
const first=frames.find(f=>f.type==='delta');assert(first?.value.results.length>0);
assert(frames.at(-1).at-first.at>900,'partial results must arrive before the slow engine');
assert.equal(frames.at(-1).value.results.length,7);
assert(frames.at(-1).value.results.some(r=>r.sourceLabel.includes('xtend fixture slow') && r.sourceLabel.includes('xtend fixture')));
rows.push({name:'canonical AppService frames, early batch, deduplication, one terminal',firstMs:first.at,finalMs:frames.at(-1).at,types:frames.map(f=>f.type)});http.dispose();

for(const [name,type] of [['chromium',chromium],['firefox',firefox]]){
 const browser=await type.launch();
 try{
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{window.__streamEvidence=[];window.addEventListener('xtend-search:stream',({detail})=>window.__streamEvidence.push({...detail,time:performance.now()}));});
  await page.goto(base);await page.waitForFunction(()=>window.XTendPage);
  await page.evaluate(()=>window.__documentIdentity='retained');
  const began=Date.now();await page.evaluate(url=>window.XTendPage.visit(url),search('stream test'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='partial');
  assert.equal(await page.locator('article.result').count(),6);
  const firstMs=Date.now()-began;
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');
  assert.equal(await page.locator('article.result').count(),7);
  assert.equal(await page.evaluate(()=>window.__documentIdentity),'retained');
  await page.waitForFunction(()=>window.__streamEvidence.some(e=>e.status==='disposed'));
  const records=await page.evaluate(()=>window.__streamEvidence);
  const finished=records.filter(e=>e.status==='disposed').at(-1);
  assert.equal(finished.transport.loader.counters.accepted,1);
  assert.equal(finished.transport.loader.counters.loaded,1);
  assert.equal(finished.transport.loader.counters.attached,1);
  assert.equal(finished.transport.activeCount,0);
  assert.equal(finished.transport.disposed,true);
  rows.push({browser:name,name:'real XScaler preflight, SRI module, progressive RMT commit and cleanup',firstMs,finalMs:Date.now()-began,transport:finished.transport});
  const streamed=await page.evaluate(()=>window.XTendPage.page.props['search.data'].results.map(r=>({id:r.id,sourceLabel:r.sourceLabel,title:r.title})));
  await page.evaluate(url=>window.XTendPage.visit(url,{headers:{'X-XTend-Stream':'off'}}),search('stream test'));
  assert.deepEqual(await page.evaluate(()=>window.XTendPage.page.props['search.data'].results.map(r=>({id:r.id,sourceLabel:r.sourceLabel,title:r.title}))),streamed);
  rows.push({browser:name,name:'final results identical to conventional upstream search'});
  await page.evaluate(url=>window.XTendPage.visit(url),search('stream old'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='partial');
  await page.evaluate(url=>window.XTendPage.visit(url),search('replacement'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');
  await page.waitForTimeout(2100);
  assert.equal(await page.evaluate(()=>window.XTendPage.page.props['search.data'].q),'replacement');
  assert((await page.locator('article.result').first().innerText()).includes('replacement'));
  rows.push({browser:name,name:'new navigation cancels XScaler; old frames cannot overwrite results'});
  await page.goBack();await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].q==='stream old' && window.XTendPage.page.props['search.data'].stream?.phase==='complete');
  await page.goForward();await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].q==='replacement' && window.XTendPage.page.props['search.data'].stream?.phase==='complete');
  rows.push({browser:name,name:'native XTend history back/forward stays resumable'});
  await page.route('**/assets/xtend/search-remote-adapter.mjs*',route=>route.abort());
  await page.evaluate(url=>window.XTendPage.visit(url),search('fallback'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].q==='fallback' && !window.XTendPage.page.props['search.data'].stream && document.querySelectorAll('article.result').length===6);
  assert.equal(await page.evaluate(()=>window.__documentIdentity),'retained');
  rows.push({browser:name,name:'adapter load failure falls back once to conventional SPA response'});
  await page.unroute('**/assets/xtend/search-remote-adapter.mjs*');
  await page.route('**/assets/xtend/search-remote-adapter.mjs*',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text())+'\nwindow.__badAdapterExecuted=true;'});});
  await page.evaluate(url=>window.XTendPage.visit(url),search('integrity fallback'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].q==='integrity fallback' && !window.XTendPage.page.props['search.data'].stream && document.querySelectorAll('article.result').length===6);
  assert.equal(await page.evaluate(()=>window.__badAdapterExecuted),undefined);
  rows.push({browser:name,name:'real browser SRI rejects modified adapter before execution'});
  await page.unroute('**/assets/xtend/search-remote-adapter.mjs*');
  await page.route('**/api/xtend/services/search.results',route=>{
   const req=route.request().postDataJSON();
   const values=frames.filter(f=>f.type==='start' || f===first).map((f,index)=>({...f,id:`broken:${index}`,streamId:req.invocationId,invocationId:req.invocationId,correlationId:req.correlationId,sequence:index+1}));
   return route.fulfill({contentType:'application/x-ndjson',body:values.map(f=>JSON.stringify(f)+'\n').join('')});
  });
  await page.evaluate(url=>window.XTendPage.visit(url),search('broken connection'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='error');
  assert.equal(await page.locator('article.result').count(),6);
  await page.locator('#search-warning-stream-error').getByRole('button',{name:'Schliessen',exact:true}).click();
  await page.locator('#search-warning-stream-error').waitFor({state:'detached'});
  rows.push({browser:name,name:'truncated stream retains received results and dismissible warning'});
  await page.unroute('**/api/xtend/services/search.results');
  await page.route('**/image_proxy?**',route=>route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="800" height="500" fill="#168b9e"/></svg>'}));
  await page.evaluate(()=>window.XTendPage.visit('/search?q=stream+media&categories=images'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='partial');
  await page.evaluate(()=>window.__streamThumbnail=document.querySelector('img[data-result-image]'));
  await page.locator('a[data-preview-id]').first().click();
  const selected=await page.locator('article[data-selected]').getAttribute('data-result-id');
  await page.locator('#preview-expand').click();await page.locator('x-lightbox[open]').waitFor();
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');
  assert.equal(await page.locator('article[data-selected]').getAttribute('data-result-id'),selected);
  assert.equal(await page.evaluate(()=>window.__streamThumbnail?.isConnected),true,'received thumbnails retain their DOM identity within the stream');
  assert.equal(await page.locator('x-lightbox[open]').count(),1);
  assert.match(await page.locator('.lightbox-position').innerText(),/von 7/);
  await page.keyboard.press('End');await page.waitForFunction(()=>document.querySelector('.lightbox-position')?.textContent==='Bild 7 von 7');
  await page.keyboard.press('Escape');
  rows.push({browser:name,name:'selected sidebar image survives batches; open XLightbox includes late images'});
  await page.evaluate(url=>window.XTendPage.visit(url),search('stream benchmark50'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');
  await page.evaluate(()=>scrollTo(0,1800));await page.waitForTimeout(100);
  await page.evaluate(url=>window.XTendPage.visit(url),search('other page'));
  await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].stream?.phase==='complete');
  await page.goBack();await page.waitForFunction(()=>window.XTendPage.page.props['search.data'].q==='stream benchmark50' && window.XTendPage.page.props['search.data'].stream?.phase==='complete');
  assert(Math.abs(await page.evaluate(()=>scrollY)-1800)<30);
  rows.push({browser:name,name:'history restores scroll after incremental content has sufficient height'});
  await page.screenshot({path:`${out}/${name}-results.png`});
  assert.deepEqual(errors,[]);
  const nojs=await browser.newContext({javaScriptEnabled:false});const native=await nojs.newPage();
  await native.goto(base+search('stream test'));assert.equal(await native.locator('article.result').count(),7);
  rows.push({browser:name,name:'no-JS initial SSR keeps complete results'});await nojs.close();
 }finally{await browser.close();}
}
fs.writeFileSync(`${out}/results.json`,JSON.stringify({timestamp:new Date().toISOString(),base,rows},null,2));
console.log(JSON.stringify({ok:true,tests:rows.length,rows},null,2));
